### ISSUE TITLE
Tidligerere bragders dokumentering

### ISSUE THREAD

**Issue by bendik** [tomtervel/nettside#1]
Som det sies i første paragraf:
> mye dokumentasjon fra virksomheten siden den gang er lagret

Så blir jeg umiddelbart nysgerrig på hvorfor denne dokumentasjonen ikke finnes på nettsiden. Ligger dokumentasjonen og blir like gulfalmet som nettsiden? 😄

Jeg tenker også at Dagens aktivitet med undeliggende:
> Vi _har_ komiteer for: x,y,z

Det kan være greit å ha som en enkel liste i stedet for en sjekkliste. Så man kan ta en konkludert komitee sine bragder til ett datert oppslag på en "historie" side. (da jeg også kan stile den som en vanlig punktliste)

**Comment by frikken** [comment]
Det som er lagret er gamle årbøker. Å skulle scanne de og legge de ut er mye arbeide og uten noen nytte for dagens problemstillinger. 

Å la hver komité få sin gren er et fremtidig alternativ. Skal lufte det på styremøtet.
